runner/browserrunner.js

This is the first part of a change that sends the pass/fail status to SauceLabs. The second part is in wct-sauce [here](https://github.com/Polymer/wct-sauce/pull/4).
This is something i wanted for my own use, but I wanted to send it back as it's a fairly small change.

Send test status (pass/fail) to SauceLabs (1/2)

---

browser.js
browser/environment/helpers.js

If an exception occurs running a test via `testImmediateAsync`, it will never
return as the `err` is updated, but `testComplete` is never set. This small
patch fixes this behaviour.

Fix testImmediateAsync catch timeout

---

browser.js
browser/childrunner.js

Fixes #101.
I removed the "prepare" function (it seemed overly complex for just one line, and the name didn't really make sense for where it is now), and i put the reference to the share variable in.

Hang a reference to the ChildRunner's iframe-local wct object

---

data/a11ySuite.js

- Supports common styles for chai
- assert style: `assert.a11yLabel(node, expectedLabel, message)`
- should/expect style: `expect(node).to.have.a11yLabel(expectedLabel, message)`
- Throws if `node` is not a Node
- Uses `axs.properties.findTextAlternatives` to calculate text label for `node`.
- Checks `textAlternative === expectedLabel`
Related: PolymerLabs/polylint#14

Add first draft of chai extensions for testing text alternatives

---

browser/mocha/replace.js

Having two tests back-to-back in TDD mode fails because the teardown step gets executed twice.
This simple fix prevents us from trying to restore an element that has already been restored.
Here's how to get a failing test. I wasn't sure how to *not* use polymer (which seems to be the norm in your tests), otherwise I would'a plopped this in the PR.
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
<script src="../../bower_components/webcomponentsjs/webcomponents.min.js"></script>
<script src="../../bower_components/web-component-tester/browser.js"></script>
<script src="../../bower_components/test-fixture/test-fixture-mocha.js"></script>
<link rel="import" …

Check if the replaced instanceTemplate needs to be restored before restoring

---

browser/mocha/stub.js

This is is the same problem as 
https://github.com/Polymer/web-component-tester/pull/251
Just a quick fix.

Only restore stubs if they are actually sinon proxies.

---

package.json
runner/httpbin.js
runner/webserver.js

Enables iron-ajax tests to be standalone and not hit the third party httpbin.org service.

Add some httpbin-like functionality to web component tester

---

package.json

I'm on Windows 10 with npm 1.4.6, and wct won't install for me.  As best I can tell from the [npm documentation](https://docs.npmjs.com/files/package.json), the test-fixture dependency is specified incorrectly.  This PR fixes that.

Fix broken reference to test-fixture repo in package.json

---

runner/browserrunner.js
runner/config.js

wct's SafariDriver help message points to a code.google.com page that no longer exists. This patch updates the message with links to the corresponding GitHub wiki pages.

Fix broken links to Selenium SafariDriver

---

runner/webserver.js

I'm currently trying to debug a rather big set of tests, which are failing due to inconsistent paths under which polymer is imported.
The verbose output of WCT isn't quite enough for that - while I can see the wrong requests, I cannot see where these come from. This PR adds the referer header to the debug output, which helps. I'm not sure whether there is any method to translate the URL back to the local path, which would be even more awesome :)

Log the referer in debug mode

---

runner/clireporter.js
runner/config.js

WCT is using its own logger, so it's going to be a little work to move off of it. Luckily theres some good stuff in here that we can bring into plylog when the time comes.
This work just adds support for the quiet option in addition to the already-supported verbose option.
/cc @justinfagnani

Add quiet CLI option

---

runner/steps.ts
test/integration/browser.ts

Fixes #375 
In the future we should have an integration test that actually shells out to `wct` and we should assert on the exit code. The integration test cleanup needs to land first though in #374

test() function must reject when any test fails.

---

.vscode/settings.json

otherwise vscode gets upset and asks you which typescript version to use everytime you open the project.
/cc @rictic @justinfagnani

signal vscode to use local typescript version

---

CHANGELOG.md
package.json
runner/context.ts
test/unit/context.ts

Fixes #373 and #383
Verified that the test fails on master and passes now.

Fix emitHook for 2-arg calls without a callback.

---

bower.json
runner/webserver.ts

Also publish bower.json and package.json to bower.
Fixes #447

Look more places for client version.

---

CHANGELOG.md
runner/config.ts
runner/webserver.ts
test/fixtures/integration/compilation/golden.json
test/fixtures/integration/compilation/test/index.html

Also hook the `webserver.hostname` flag back up, as it turns out it's used.
Fixes #437
/cc @azakus

Use polyserve's ESNext -> ES5 compilation.

---

browser/mocha/stub.js

Use the returned stub returned from sinon to restore, since when stubbing getter/setter properties there isn't an isSinonProxy property to check.
Closes #471

fix(stub): Properly restore stubbed *etter methods

---

CHANGELOG.md
README.md
data/a11ySuite.js

- This is a follow-up to https://github.com/Polymer/web-component-tester/pull/493
- @lukeschaefer's original PR description:
> As per issue #392, parts of the page may be missing while a11ySuite runs, since `Polymer.dom.flush()` is never called.
>
>Without Polymer.dom.flush, fixtures with elements containing dom-repeat or dom-if templates would not be fully loaded. In many cases, this results in running the test suite on only a fragment of the page, missing possible errors. In few cases, it would trigger possible errors, for example:
>
> ```html
> <div role='radiogroup'>
>   <template is='dom-repeat'>
>      <ul role='radio'>Button</ul>
>   </template> 
> </div>
> ```
> The test suite would incorrectly think the radiogroup had no role='radio' children.
>
> Also, this adds in a beforeEach …

Add `Polymer.dom.flush()` before each test.

---

CHANGELOG.md
runner/webserver.ts

`wct` is slow to install, and having a local node install of it doesn't actually buy us much. The vastly more important thing is that users have the expected client-side dependencies, as wct's server-side semantics don't change enough to make this worth the cost in installation time and hassle.
Fixes #486 
Other discussion at #444 (and one other with @cdata IIRC, though I can't find that at present).

Remove the warning about no local node_modules install of wct.

---

test/fixtures/early-failure/test/index.html
test/fixtures/integration/compilation/test/index.html
test/fixtures/integration/components_dir/test/index.html
test/fixtures/integration/failing/golden.json
test/fixtures/integration/failing/test/index.html
test/fixtures/integration/failing/test/tests.html
test/fixtures/integration/hybrid/test/index.html
test/fixtures/integration/hybrid/test/tests.html
test/fixtures/integration/inline-js/test/index.html
test/fixtures/integration/many-html/test/index.html
test/fixtures/integration/many-html/test/one.html
test/fixtures/integration/many-html/test/three.html
test/fixtures/integration/many-html/test/two.html
test/fixtures/integration/many-js/test/index.html
test/fixtures/integration/missing/test/missing.html
test/fixtures/integration/multiple-component_dirs/golden.json
test/fixtures/integration/multiple-component_dirs/test/index.html
test/fixtures/integration/multiple-replace/test/index.html
test/fixtures/integration/multiple-replace/test/tests.html
test/fixtures/integration/nested/test/index.html
test/fixtures/integration/nested/test/leaf.html
test/fixtures/integration/nested/test/one/index.html
test/fixtures/integration/nested/test/one/tests.html
test/fixtures/integration/nested/test/two/index.html
test/fixtures/integration/no-tests/test/index.html
test/fixtures/integration/one-html/test/index.html
test/fixtures/integration/one-html/test/tests.html
test/fixtures/integration/one-js/test/index.html
test/fixtures/integration/query-string/test/index.html
test/fixtures/integration/query-string/test/tests.html

- Only tests were modified and only slightly.
- specifically `<script src="../../../browser.js"></script>` became `<script src="/components/web-component-tester/browser.js"></script>`.
- VS Code made some formatting adjustments to HTML and JSON indentation that were innocuous and consistent so I was fine not trying to undo those.
- no CHANGELOG.md updates needed.

Updated test fixtures for integration tests so they wouldn't trigger the deprecation warning on requesting '/browser.js'

---

CHANGELOG.md

- Only update was sinon dependency change to browser-ready version.

Updated CHANGELOG for 6.1.1 release

---

CHANGELOG.md
package.json

- Set `@polymer/test-fixture` back to ^0.0.3 because of dependency install errors related to yarn's "flat".
- Fixes https://github.com/Polymer/web-component-tester/issues/598

Set test-fixture back to ^0.0.3

---

CHANGELOG.md

This is a critical release because it resolves errors installing wct via yarn due to https://github.com/Polymer/web-component-tester/issues/598
* Added `sinon` as dependency of `sinon-chai` in web context to suppress the npm installation warning/error of unmet peer dependency, even though `@polymer/sinonjs` fulfills the runtime dependency and `sinon` will be unused.
* Set `@polymer/test-fixture` back to ^0.0.3 because of dependency install errors related to yarn's "flat".

Updated CHANGELOG for 6.1.3 release.

---

CHANGELOG.md

- Removed reliance on `document.currentScript` in browser.js because IE11 doesn't have it.  Fixes [Issue #602](https://github.com/Polymer/web-component-tester/issues/602)
- To use WCT tests with NPM in browser without WCT (or polymer-cli) running on the commandline, you must include an `?npm=true` or `&npm=true` parameter in the URL for the test document; WCT does this automatically when opening its own browsers.

Updated CHANGELOG for 6.1.4 release.

---

CHANGELOG.md

- Removed reliance on `document.currentScript` in browser.js because IE11 doesn't have it. (Second reference found)

Update CHANGELOG for 6.1.5 release.

---

runner/cli.ts
runner/clireporter.ts
runner/config.ts
runner/context.ts
runner/paths.ts
runner/webserver.ts
test/integration/browser.ts
test/unit/context.ts
test/unit/paths.ts

I did a clean install of dependencies, and then ran clang-format. It looks like some formatting rules may have changed /shrug.

re-run clang-format

---

CHANGELOG.md
bower.json
package-lock.json
package.json
wct-browser-legacy/package.json

* Updated the browser.js file for npm case to use test-fixture as JS module instead of html import.
* Updated the integration tests to support running on Sauce via wct-sauce plugin.
* Updated polyserve to 0.22.0 for better compilation support and ES modules in HTML script tags.
* Updated bower.json to use test-fixture 3.0.0!
* No longer require `?npm=true` url parameter, as `web-component-tester` and `wct-browser-legacy` versions of `browser.js` now contain explicit npm/non-npm directives of the form `window.__wctUseNpm` as a first step towards splitting out the client-side environment-specific config and behavior.
* Added support for scoped package names under npm.

Prepare release 6.2.0

---

CHANGELOG.md
package-lock.json
package.json

* Updated wct-browser-legacy to use a module version of a11ySuite to get access to Polymer.dom.flush.
* Updated generated index for webserver to use a11ySuite as a module.
* Updated polyserve to get support for on-the-fly module compilation and `<script type=module>` conversion for browsers that don't support modules.

Prepare Release 6.3.0

---

wct-browser-legacy/package.json

Since a11ySuite.js imports it, I've made `@polymer/polymer` a dependency of `wct-browser-legacy` "^3.0.0-pre.1"

Add @polymer/polymer to wct-browser-legacy dependencies

---

CHANGELOG.md

* Updated package.json:
* Upgraded dependencies async, chai, cleankill, findup-sync, sinon, and socket.io.
* Upgraded devDependencies update-notifier
* Added `define:webserver` hook to enable substitution of the generated express app for the webserver through a callback, to support use cases where a plugin might want to inject handlers or middleware in front of polyserve.
* Added support for `proxy: {path: string, target: string}` config which is forwarded to `polyserve`.

Updated CHANGELOG for Halloween release of WCT 6.4.0

---

browser/reporters/html.ts

This seems to be slowing down testing in Polymer and provides no
discernable visual difference in the test output

Remove unnecessary overflow-y: auto

---

CHANGELOG.md
runner/webserver.ts

Replace hardcoded `localhost` to use the webserver hostname option.
This change allows users to utilise their own selenium grid as opposed to sauce labs.

WCT uses webserver.hostname (#523)

---

CHANGELOG.md
package-lock.json
wct-browser-legacy/package.json

- updates wct
- updates wct-browser-legacy
- needed for npm element test passing

prepare v6.4.3

---

CHANGELOG.md

* Upgrade wct-local to 2.1.0 to get support for headless Chrome.

Updated CHANGELOG for 6.5.0 release.

---

browser/childrunner.ts

This converts some errors that look like `Test run ended in failure: Error thrown outside of test function: Cannot read property 'WCT' of null`
into ones that look like `Timed out loading http://localhost/:17604/components/my-component/test.html`

Handle content loading timeouts more gracefuly.

---

.travis.yml
gulpfile.js
test/fixtures/integration/components_dir/wct.conf.json
test/fixtures/integration/custom-components_dir/test/index.html
test/fixtures/integration/custom-multiple-component_dirs/test/index.html
test/integration/browser.ts

* `TEST_LOCAL_BROWSERS=chrome,firefox`
* `TEST_REMOTE_BROWSERS=OS X 10.12/safari@11`
Integration tests already support `SKIP_LOCAL_BROWSERS` and `SKIP_REMOTE_BROWSERS`.

Add env vars to specify which browsers to test in integration tests.
