Polymer/web-component-tester

README.md
=> Make wct a link

browser.js
by deferring testing until dependencies are fully loaded, specifically mocha's css file.
=> Fixes #172

package.json
=> Include grunt task with npm install

runner/webserver.js
=> Work around Firefox + Windows relative iframe path issue.

README.md
=> Prefer wct.conf.json

README.md
For sauce you need to send in more browser configuration than is currently listed in the readme
=> Fix incorrect sauce syntax

README.md
=> Update README to use webcomponents-lite.js

bower.json
Sort dependencies, update chai to v3 like wct uses
=> Update bower dependencies

test/unit/cli.js, test/unit/grunt.js
Depends on https://github.com/Polymer/wct-local/pull/32 having been merged and released for travis to actually become green though.
=> Fix wct local stubs

.clang-format, .vscode/settings.json, package.json, runner/browserrunner.ts, runner/cli.ts, runner/clireporter.ts, runner/config.ts, runner/context.ts, runner/gulp.ts, runner/httpbin.ts, runner/paths.ts, runner/plugin.ts, runner/port-scanner.ts, runner/steps.ts, runner/test.ts, runner/webserver.ts, test/integration/browser.ts, test/unit/cli.ts, test/unit/config.ts, test/unit/context.ts, test/unit/grunt.ts, test/unit/gulp.ts, test/unit/paths.ts
=> Format all code with clang-format

.gitignore, .vscode/settings.json, package.json, runner/config.ts, runner/context.ts, runner/httpbin.ts, runner/plugin.ts, tsconfig.json
=> Improve and standardize our typescript config

runner/config.ts, runner/context.ts, runner/paths.ts, test/integration/browser.ts, test/unit/paths.ts
no-op, will reduce diff in upcoming polyserve PR
/cc @justinfagnani @rictic
=> clang-format repo

CHANGELOG.md, runner/webserver.ts, test/integration/setup_test_dir.ts
=> Warn if wct is not installed locally in node_modules.

runner/browserrunner.ts, runner/steps.ts, test/integration/browser.ts
Fixes #459 (see that bug and the comments in this PR for the details).
=> Support Safari 10 and variants

package.json
=> Update client-side-version-range with new prerelease tag

package.json, test/integration/browser.ts
This works, our integration tests cover this.
=> Update the client version range

CHANGELOG.md, runner/config.ts
created in https://github.com/Polymer/web-component-tester/commit/574e4d8aefd0fcd776fc7151e84630404789367b
=> Fix error log template string typo

runner/steps.ts
Made the browser options do a deep clone instead of a shallow one to allow more options through
=> Deep merge of browser options

bower.json
It's a brave new world out there. 
@justinfagnani @cdata
=> New week, new test-fixture version

CHANGELOG.md
The actual commit to review is d124297 which I accidentally pushed to master -.-
Valdrin's commit 7d0c9d6fab1ac744f1d5eee96ca35735405e44c6
=> Prepare to release 6.0.0-prerelease.6

runner/browserrunner.ts, runner/cli.ts, runner/context.ts, runner/webserver.ts, test/integration/browser.ts, test/unit/context.ts
I didn't want to include these in the prior PR.  This is just a batch of formatting corrections by clang-format.
=> Ran npm run format and these were the changes.

package.json
=> 6.0.0-prerelease.8

test/unit/cli.ts, test/unit/grunt.ts, test/unit/gulp.ts
=> Fix tsc 2.3.0 warnings.

package.json
=> update polyserve to 0.19.0

CHANGELOG.md, bower.json
=> Prepare to release v6.0.0

runner/context.ts, test/integration/browser.ts
Noticed these while working on a couple other PRs and figured I could clean them up since you guys are swamped!
/cc @justinfagnani @rictic
=> Update: Clean up a couple TODOs

package-lock.json, package.json, wct-browser-legacy/package.json
=> Updated package.json to point to @polymer/test-fixture v0.0.1-pre.3

.travis.yml, CHANGELOG.md, test/fixtures/integration/failing/golden.json, test/fixtures/integration/multiple-component_dirs/golden.json, test/fixtures/integration/query-string/golden.json, test/fixtures/integration/query-string/test/index.html, test/fixtures/integration/query-string/test/tests.js, test/integration/browser.ts
- Note that IE and Safari apparently report line numbers in stack traces differently, so had to account for this in two of the golden.json files.
=> Add Sauce support to integration tests (so WCT tests itself on windows and safari)

runner/config.ts, runner/webserver.ts
Add packageName handling, that can handle NPM scoped packages. Do this instead of reading from the cwd.
=> Fix broken npm scoped package support

CHANGELOG.md, runner/config.ts, runner/webserver.ts
`proxy-path` and `proxy-target`
https://github.com/Polymer/web-component-tester/issues/607
=> Forward proxy config to the polyserve

CHANGELOG.md, package-lock.json, package.json, runner/context.ts, runner/webserver.ts, test/fixtures/integration/define-webserver-hook/golden.json, test/fixtures/integration/define-webserver-hook/test/index.html, test/fixtures/integration/define-webserver-hook/test/tests.html, test/integration/browser.ts
- Allows a callback to reassign the express application to provide mechanism to front polyserve with alternate request handlers and middleware.
=> Add define:webserver hook

CHANGELOG.md, package.json
=> Bump wct-local and wct-sauce versions. Stamp patch release.

package.json
=> Update wct-local to 2.1.0

CHANGELOG.md, package-lock.json, package.json, runner/config.ts, runner/webserver.ts
=> Update polyserve to 0.24.0 add the --module-resolution flag

CHANGELOG.md, custom_typings/bower-config.d.ts, package-lock.json, package.json, runner/webserver.ts, test/fixtures/integration/custom-components_dir/.bowerrc, test/fixtures/integration/custom-components_dir/golden.json, test/fixtures/integration/custom-components_dir/my_components/bar-element/bar-element.js, test/fixtures/integration/custom-components_dir/test/index.html, test/fixtures/integration/custom-multiple-component_dirs/.bowerrc, test/fixtures/integration/custom-multiple-component_dirs/golden.json, test/fixtures/integration/custom-multiple-component_dirs/my_components-bar/package/index.js, test/fixtures/integration/custom-multiple-component_dirs/my_components-foo/package/index.js, test/fixtures/integration/custom-multiple-component_dirs/my_components/package/index.js, test/fixtures/integration/custom-multiple-component_dirs/test/index.html, test/integration/setup_test_dir.ts
Fixes #488
Honors the .bowerrc file for determining the name of the bower_components directory.
Also supports variants using the .bowerrc directory setting, however, this depends on https://github.com/Polymer/polyserve/pull/206
=> Add support for .bowerrc

runner/config.ts
=> remove console log

CHANGELOG.md, package-lock.json, package.json
=> Prepare 6.6.0-pre.4 release.
